version: 0.2

phases:
  install:
    commands:
      - npm install -g sass
  pre_build:
    commands:
      - chmod +x build.sh
  build:
    commands:
       - bash build.sh
  post_build:
    commands:
      - ls -l
artifacts:
  files:
    - '**/*'
